### ISSUE TITLE
Improve the Footer Section 

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#1]
**Show your creativity and change the UI for the footer.**

**Comment by Sugyanee** [comment]
hey, can I work on this issue?

**Comment by saloni-15** [comment]
sure @Sugyanee

**Comment by Ayan-thecodeking** [comment]
Assign me... If this is not done then @saloni-15

**Comment by saloni-15** [comment]
@Sugyanee are you working on it?

**Comment by Sugyanee** [comment]
> @Sugyanee are you working on it?

Yes, I am working on it.

**Comment by yogesh2k21** [comment]
Please assign me... If this is still not done @saloni-15
