### ISSUE TITLE
Make Footer Responsive 

### ISSUE THREAD

**Issue by codersalman** [saloni-15/Heel2Toe#103]
![Screenshot_20211005_150530.jpg](https://user-images.githubusercontent.com/83803180/135998707-2c5fbab1-4825-4fd6-947f-bf9186ee139f.jpg)

Footer is distributed

**Comment by saloni-15** [comment]
ok @codersalman

**Comment by ask2rg** [comment]
![image](https://user-images.githubusercontent.com/88713855/136265422-059c5c17-502e-4bc4-8e11-89e79c962318.png)
there are lot of ui and responsiveness issues check header, footer, products cards when window size is 750px-950px

**Comment by codersalman** [comment]
Hey @saloni-15  I Made a Responsive Footer 

![image](https://user-images.githubusercontent.com/83803180/136551434-a95ba447-e71d-4d9b-ad7a-27d702d2325d.png)


![image](https://user-images.githubusercontent.com/83803180/136551568-41f2b8f6-35e7-49b6-9015-b8770241929f.png)

**Comment by codersalman** [comment]
Now the Footer is Responsive but the product cards are disturbing the website's responsiveness coz the product cards are not responsive 


We need to make the product cards responsive first 

# Without Product Cards 

![Screenshot_20211008_183316.jpg](https://user-images.githubusercontent.com/83803180/136562204-86a671ae-9b15-4007-a592-18562bd6293e.jpg)

#With Products Cards 
![Screenshot_20211008_183323.jpg](https://user-images.githubusercontent.com/83803180/136562282-ba303484-95dd-4e2e-8e99-7d23a46788b6.jpg)

@saloni-15

**Comment by codersalman** [comment]
After Responsive Products card I'll create  PR

**Comment by rohitdubey1352** [comment]
Hey, @saloni-15 I would like to make it responsive on all devices, Assign me this task if exist...

**Comment by codersalman** [comment]
@rohitdubey1352 you can

**Comment by rohitdubey1352** [comment]
Thanks, I will do my work and submit it ASAP

**Comment by codersalman** [comment]
![Screenshot from 2021-10-15 17-48-31](https://user-images.githubusercontent.com/83803180/137485563-0df0eea4-343b-4022-8dbd-d25ab712ad52.png)


the cards are overlaping each other
and in mobile its looking odd
