### ISSUE TITLE
[Issue] : Update responsive navbar on other pages

### ISSUE THREAD

**Issue by thanh-cao** [saloni-15/Heel2Toe#104]
### Issue Description

Navbar is currently not consistent and responsive on women.html, men.html, arrivals.html as compared to index.html. In the image below is from women.html for example. I would like to fix this.

![Screen Shot 2021-10-05 at 12 04 02 PM](https://user-images.githubusercontent.com/55603278/136003589-8122cf5f-d652-4cf0-b235-1bdff4057c91.png)

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
sure @thanh-cao
