### ISSUE TITLE
[Issue] : Trending navigation bar & bestseller section navbar 

### ISSUE THREAD

**Issue by user23ayush** [saloni-15/Heel2Toe#107]
### Issue Description

 Trending navigation bar Heel2toe brand in navbar doesn't return to homepage and bestseller section navbar styling plus navbar doesn't have a brand name and no way to return to home page.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by user23ayush** [comment]
Kindly assign me this issue

**Comment by saloni-15** [comment]
Sure @user23ayush
