### ISSUE TITLE
make Navbar responsive 

### ISSUE THREAD

**Issue by Krishnapro** [saloni-15/Heel2Toe#125]
### Issue Description

navbar is not responsive in every screen size make

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by Tanujkanti4441** [comment]
Can i work on it please

**Comment by saloni-15** [comment]
@Krishnapro, you raised the issue for your assignment? Do you want to work on this issue?

**Comment by Krishnapro** [comment]
It is accepted in hacktoberfest @saloni-15
