### ISSUE TITLE
Images are too big and loading gets sluggish

### ISSUE THREAD

**Issue by kashish-d** [saloni-15/Heel2Toe#13]
## 📝DESCRIPTION 
-Images sizes can be compressed to make the performance better. Lazy loading can be implemented to load images as we scroll to reduce the initial load time. And we can apply a preloading animation to load contents on the page properly before showing.

## 📸Provide related Screenshot/Gifs if any.
- [x] I'm a contributor in Hacktoberfest'21.

**Comment by kashish-d** [comment]
I would like to make this better, if you agree, can i work on this issue?

**Comment by saloni-15** [comment]
Sure @kashish-d, there's much need to get this thing done 😃, thankyou for raising this issue.

**Comment by kashish-d** [comment]
Great, I will start working on it!😄
