### ISSUE TITLE
Improve Readme.me

### ISSUE THREAD

**Issue by rishabhrathore055** [saloni-15/Heel2Toe#15]
## 📝DESCRIPTION 
-
Hello @saloni-15   Can I improve the Documentary of the project, If needed then kindly assign issue

## 📸Provide related Screenshot/Gifs if any.
- [x] I'm a contributor in Hacktoberfest'21.

**Comment by saloni-15** [comment]
sure @rishabhrathore055

**Comment by Ayan-thecodeking** [comment]
Hey I'm up for this 
Can you pls assign me 
@saloni-15
