### ISSUE TITLE
[🐛Bug] : Nav link hover issue on New Arrivals page.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#153]
### Issue Description

**We can see on hovering the nav links on the `New Arrivals` page i.e `arrivals.html`, the links get shown in blue color, that's not what we want, it should be white only. Please check what's the issue and resolve this :)**

![image](https://user-images.githubusercontent.com/75828760/137482751-7ed7fecd-7d16-44aa-afc1-22726026becd.png)

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by sparsh-30** [comment]
I can fix this issue. Please assign this to me.

**Comment by saloni-15** [comment]
ok @sparsh-30
