### ISSUE TITLE
Contact form not responsive

### ISSUE THREAD

**Issue by the-eduek** [saloni-15/Heel2Toe#166]
### Issue Description

The contact form is not responsive. It only appears to work when you shrink size.
It isn't actually responsive when opened on smaller screens. I would love to work on this issue.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
sure @the-eduek

**Comment by the-eduek** [comment]
@saloni-15 I'm sorry it's taken me such a long time to fix this. I've been struggling with the file structure as the main style.css overrides all changes I made in the contact.css file and I cannot unlink the main CSS file as it contains all global styles.

If someone else has made a PR for this issue, merge it so I could learn how they did it. 

Again, I'm sorry.

**Comment by saloni-15** [comment]
No problem @the-eduek, it's fine.
