### ISSUE TITLE
Fix navbar on product's page.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#182]
### Issue Description

**Navbar on the `Product`'s page is very odd from others.**
https://saloni-15.github.io/Heel2Toe/product.html

**Please make it the same as on other pages other than the one on the homepage.**

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by shidoitsuka** [comment]
@saloni-15 Check out my PR.
It looks even better now, I suppose
