### ISSUE TITLE
Issue with Women's section

### ISSUE THREAD

**Issue by LaLiLuLeLoPS** [saloni-15/Heel2Toe#19]
## 📝DESCRIPTION 
-
Hey @saloni-15 I love your website both from a functional standpoint as well as design.
One issue I noticed was the redirection to the "women's" section was broken.
In the spirit of Hacktober, could you assign this task to me as part of the event?
cheers :)

- [x] I'm a contributor in Hacktoberfest'21.

**Comment by saloni-15** [comment]
ok @LaLiLuLeLoPS
