### ISSUE TITLE
Add a "back-to-top" button.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#2]
**When we scroll up the website, there should come a button which when clicked moves us to the top of the website.**

**So, add that button 🎇**

**Comment by amanr11314** [comment]
Hey an I take this issue?

**Comment by srija920** [comment]
Hello, would you like to assign this task to me?

**Comment by saloni-15** [comment]
@srija920 Please, look for the issues that are not assigned to anyone.
