### ISSUE TITLE
issue-forms

### ISSUE THREAD

**Issue by salmangada** [saloni-15/Heel2Toe#20]
## 📝DESCRIPTION 
- GitHub has recently rolled out a public beta for their issue forms feature. This would allow you to create interactive issue templates and validate them . Can I update the same for this project.

- [x] I'm a contributor in Hacktoberfest'21
![Capture](https://user-images.githubusercontent.com/70872374/135565483-581ff2f3-d653-4603-ac95-1ee7def243ca.PNG)
.

**Comment by saloni-15** [comment]
ya sure @salmangada
