### ISSUE TITLE
Add Navbar to women.html page

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#31]
## 📝DESCRIPTION 
- Add a navbar to the `women.html` page keeping in mind the homepage's theme.
- Please note to not make it very fancy😥
- Do share the screenshot or gif while making a PR.

## 📸Provide related Screenshot/Gifs if any.
<hr/>

- [x] I'm a contributor in Hacktoberfest'21.

**Comment by Nutan2305** [comment]
I would like to work on this issue

**Comment by kashish-d** [comment]
Can i get this issue?

**Comment by saloni-15** [comment]
Sure @Nutan2305, 
and @kashish-d, you can take up any other issue or can create one 😅, we now have a whole page to design, you can come up with more ideas.

**Comment by kashish-d** [comment]
Oh for sure!😄

**Comment by kashish-d** [comment]
Great! I will start working on this.
