### ISSUE TITLE
Add aboutUs page 

### ISSUE THREAD

**Issue by swag1223** [saloni-15/Heel2Toe#33]
## 📝DESCRIPTION 
-
we can add something like about us page where we can display the reviews of our customers about our services.

## 📸Provide related Screenshot/Gifs if any.
- [x] I'm a contributor in Hacktoberfest'21.

**Comment by kashish-d** [comment]
Can i work on this?

**Comment by saloni-15** [comment]
there are already many pages, we will have to design them first, so for now I'm not considering adding the "AboutUs" page too.
