### ISSUE TITLE
Improve the contact form.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#34]
## 📝DESCRIPTION 
- Improve and style the Contact form in `contact.html` themed with the homepage.
- Please don't make it very fancy.🙂
- Try to make it responsive.
- You can add or remove any form input.
- Give it a heading of `Contact` with the fonts already used in the project.
- Do provide the screenshot/gif while making PR :)

## 📸Provide related Screenshots/Gifs if any.
![image](https://user-images.githubusercontent.com/75828760/135618883-821526f1-4599-47ec-aa23-3bc31330cfc0.png)

<hr/>

- [x] I'm a contributor in Hacktoberfest'21.

**Comment by x-walker-x** [comment]
Hey, I am interested.

**Comment by saloni-15** [comment]
@sunidhisachan sure

**Comment by saloni-15** [comment]
> Hey, I am interested.

First one to comment will get assigned first :)

**Comment by swag1223** [comment]
i feel we should have place an order form instead of contact form , because contact info is already provided in the footer!!

**Comment by saloni-15** [comment]
> i feel we should have place an order form instead of contact form , because contact info is already provided in the footer!!

thanks for the suggestion, we can consider this later.

**Comment by AnshumanDhiman** [comment]
Hi i've done minor changes can this get accepted ??

**Comment by AnshumanDhiman** [comment]
:(

**Comment by sunidhisachan** [comment]
> @sunidhisachan sure

Thanks
