### ISSUE TITLE
Add "Best Sellers" Page

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#36]
## 📝DESCRIPTION 
- Create a blank `best.html` page and on the home page, add nav li "BEST SELLERS" to the navbar before "CONTACT" and link "BEST SELLERS" of the navbar to redirect to `best.html`.
- Provide the screenshot while making PR.

## 📸Provide related Screenshots/Gifs if any.
![image](https://user-images.githubusercontent.com/75828760/135633699-633485af-9089-4a32-8d77-0bbd498bc629.png)

- [x] I'm a contributor in Hacktoberfest'21.

**Comment by ramyamahi** [comment]
Please assign this to me @saloni-15

**Comment by saloni-15** [comment]
sure @ramyamahi

**Comment by ramyamahi** [comment]
@saloni-15 Please check the PR #39
