### ISSUE TITLE
✨Designing the "Best Sellers" Page✨

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#44]
### Issue Description
**Designing the "BEST SELLERS" page.**
## Styling ideas
- You can include a self-moving Carousel/Image-slider having footwear-related images making it like a kind of commercials.
- And for smaller size images, you can use images from assets or you can add images from other sources.
- Include both men's and women's footwear.
- Use the same theme as the homepage.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by salmangada** [comment]
Hii, you can assign to me this task.

**Comment by salmangada** [comment]
@saloni-15 
you can assign this task to me

**Comment by saloni-15** [comment]
sure @salmangada
