### ISSUE TITLE
[Issue] : improving footer

### ISSUE THREAD

**Issue by arunsingh009** [saloni-15/Heel2Toe#54]
### Issue Description

Footer is not looking good + it is not responsive too
![footer bug](https://user-images.githubusercontent.com/66819980/135677976-43be9495-d56b-4e8e-940f-b92e4cd33079.png)
 

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by arunsingh009** [comment]
if you find this isuue valid then please assign this task to me

**Comment by arunsingh009** [comment]
@saloni-15 i am new into this open source world if i did some error in like openinig or closing of pr's then please don't mind it

**Comment by saloni-15** [comment]
@arunsingh009 no problem
