### ISSUE TITLE
[contribution permission] : Hello, Can I design & create a product page?

### ISSUE THREAD

**Issue by Diptenusarkar** [saloni-15/Heel2Toe#56]
### Issue Description

Hello Saloni!
I can see this e-commerce website does not have a single product page, so can I create one.
and also I would like to implement some basic animation & some minor issues.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
sure @Diptenusarkar

**Comment by Diptenusarkar** [comment]
Thank You for your permission @saloni-15 
But I have one question regard pull request.

**Comment by saloni-15** [comment]
> Thank You for your permission @saloni-15 But I have one question regard pull request.

what question?

**Comment by Diptenusarkar** [comment]
Actually, I'm looking for how to add a checkbox.
Now I finally got it.

**Comment by saloni-15** [comment]
> Actually, I'm looking for how to add a checkbox. Now I finally got it.

ok, hey can you please don't change the homepage's look, just work on styling the product page, you can remove the edits for the navbar on the homepage and that two buttons there, don't change the styling for the home page.

**Comment by Diptenusarkar** [comment]
Sure, Just me some time to figure it out.

**Comment by Diptenusarkar** [comment]
Hello, @saloni-15  Update Done.
