### ISSUE TITLE
Fix contact form

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#58]
### Issue Description

- The contact page shows 2 same forms, remove the second one.
- Change the color of the body of the contact form and make it same as the homepage's body color.

![image](https://user-images.githubusercontent.com/75828760/135705634-411bc301-74bb-4d82-8db0-6bea0574ec81.png)

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by bairwa25** [comment]
@saloni-15  can I work on this?

**Comment by saloni-15** [comment]
sure @bairwa25
