### ISSUE TITLE
Add anchor style for address in footer section

### ISSUE THREAD

**Issue by nurulramadhona** [saloni-15/Heel2Toe#59]
### Issue Description

I see that the color of email address (linked text) has different color than others and is underlined as well in every page that contains footer section. So, I wanna add address class and set its styles there to change the color and remove the underlined effect. It'll make change to existing and every new page created that contains footer section as well. 

For now, it's on home and trending page.

![Screenshot_76](https://user-images.githubusercontent.com/29436427/135706409-5e2420ac-a193-4740-bcac-ea2c279cfaf3.png)

![Screenshot_75](https://user-images.githubusercontent.com/29436427/135706411-21a4ae37-1d77-4a66-b00e-6f6e1f4e5770.png)

If you find this issue valid, please assign to me.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
also please add the link to `Best Sellers` and `Trending` pages to the footer in order same as Navbar.

**Comment by nurulramadhona** [comment]
I already add address class and link for trending and best sellers on the footer as well. Please check my pull request #62 

Thank you

**Comment by nurulramadhona** [comment]
I've fixed the conflicts and create new pull request #66 because I've removed previous branch. Please check the new one. Thank you.
