### ISSUE TITLE
Add Smooth Scroll to the Web Page

### ISSUE THREAD

**Issue by CodesbyUnnati** [saloni-15/Heel2Toe#6]
Hey Saloni! I  found your website really cool and want to contribute to your repo as a part of Hacktoberfest. I want to add **Smooth Scroll** and some **CSS styling**( like designing the scroll bar, etc) to your webpage as it will look good.
Can u please assign this issue to me.
Thank You! :)

**Comment by saloni-15** [comment]
Why not @CodesbyUnnati ... Go for it...💯

**Comment by saloni-15** [comment]
Hey, just make sure to work on styling single component only like scroll bar as we can have more issues for different components.
