### ISSUE TITLE
[Issue] : "Trending" page footer background

### ISSUE THREAD

**Issue by bairwa25** [saloni-15/Heel2Toe#65]
### Issue Description

Footer background is not correct.

![image](https://user-images.githubusercontent.com/43534798/135710435-32fa2cb2-aa8e-4e53-b20f-ca4f994172ee.png)

@saloni-15 can I fix this?

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
yes sure, make it same as that of the homepage's one
