### ISSUE TITLE
Adding a poster in women's section

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#67]
### Issue Description

- Include a banner/poster related to women's footwear on the `women.html` page at the top of the page just below the navbar.
- Something like this
![image](https://user-images.githubusercontent.com/75828760/135712678-7f29a5d9-bc2f-44e0-ab6d-eb0e6328adfd.png)
- Please share the screenshot while creating the PR

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by soumali28** [comment]
I want to do this. Please assign it to me

**Comment by saloni-15** [comment]
sure @soumali28
