### ISSUE TITLE
Sync NavBar & Footer Links

### ISSUE THREAD

**Issue by nurulramadhona** [saloni-15/Heel2Toe#73]
### Issue Description

1. Some of tab menu's links in index.html are directing to other page outside index.html where they should be directed to index.html id.

2. Tab menu's links in other pages *.html (except index.html) are directing to their each own id where they should be directed to their own URL. 

For example: I click the MEN menu on trending page, it's directed to id "#men" of trending.html where it should be directed to it's own page like men.html. 

![Screenshot_99](https://user-images.githubusercontent.com/29436427/135721695-df301559-34c5-42c3-882c-2190a1fd3b66.png)

By making this change to trending.html menu's links, you can let anyone who wanna add menu's section on the page they created by copying the code from trending.html instead of index.html because menu's links on homepage is different with other page (homepage is using id and other pages are using URL). It's a safer way to reduce misdirection page. I also need to create blank html file for each page doesn't exist yet to attach them on trending page's menu section and update all explore button's links on home page.

If you find this issue valid, please assign to me.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
update the link to redirect to respected pages in existing navbars and footers and sections on the homepage.

**Comment by nurulramadhona** [comment]
I've done it on #77 
Please check. 
Thank you.
