### ISSUE TITLE
[Issue] : footer section again messed up

### ISSUE THREAD

**Issue by arunsingh009** [saloni-15/Heel2Toe#74]
### Issue Description

i can update it again someone changed the layout which is creating conjusted view when we see in smaller screen if this is valid issue then  please assign this task to me.
![messfooter2](https://user-images.githubusercontent.com/66819980/135722672-bb3fe01a-fff4-417d-acf1-400d7546bd7a.png)
![messfooter1](https://user-images.githubusercontent.com/66819980/135722677-22df2a74-de83-43d2-b019-9c9c383aae67.png)

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by saloni-15** [comment]
hey, also, please change these texts to thinner size, these are kinda huge, try to make it minimalistic.

**Comment by arunsingh009** [comment]
is it looking good or need some other changes if you want any other change please do let me know

![messfooter done](https://user-images.githubusercontent.com/66819980/135746689-3e456bfb-caf8-464d-ab5e-d27afb7e9df6.png)

**Comment by saloni-15** [comment]
it looks good.
