### ISSUE TITLE
Adding poster to men's section.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#75]
### Issue Description

- Include a banner something like this on the men's page

![image](https://user-images.githubusercontent.com/75828760/135724255-6d065342-9439-4f90-828a-a22fff381d62.png)

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by shutupRohit** [comment]
Hey, can i work on this issue ?

**Comment by shutupRohit** [comment]
can you provide me the poster or should i use any suitable free poster ?

**Comment by saloni-15** [comment]
> can you provide me the poster or should i use any suitable free poster ?

you can use any men's footwear-related image from the internet as the background image, and over it, you can write styling with CSS.

**Comment by satyam73** [comment]
Hello @saloni-15  can i add this

**Comment by saloni-15** [comment]
sure @satyam73

**Comment by satyam73** [comment]
![will-breen-QbDe8JxtUp0-unsplash](https://user-images.githubusercontent.com/85296770/135727179-4823bac2-14b0-48ab-a7ad-7e24a25e3f37.jpg)
Can I add this? @saloni-15

**Comment by satyam73** [comment]
Hello @saloni-15 please tell me about this so I can start with this.
Q1. Can I use this image?
Q2. Do I have to add some text over image with css styling?

> ![will-breen-QbDe8JxtUp0-unsplash](https://user-images.githubusercontent.com/85296770/135727179-4823bac2-14b0-48ab-a7ad-7e24a25e3f37.jpg) Can I add this? @saloni-15

**Comment by saloni-15** [comment]
> Hello @saloni-15 please tell me about this so I can start with this. Q1. Can I use this image? Q2. Do I have to add some text over image with css styling?
> 
> > ![will-breen-QbDe8JxtUp0-unsplash](https://user-images.githubusercontent.com/85296770/135727179-4823bac2-14b0-48ab-a7ad-7e24a25e3f37.jpg) Can I add this? @saloni-15

yes you can add this image and yes you have write over the image

**Comment by satyam73** [comment]
Hello @saloni-15 , I have created this.
Is this is good?
![navposter](https://user-images.githubusercontent.com/85296770/135766888-d8f60298-83aa-48d2-870a-c3027323edc4.PNG)

**Comment by saloni-15** [comment]
yes, it looks good
