### ISSUE TITLE
Unaligned elements in footer and "quick links" looks like a link

### ISSUE THREAD

**Issue by InternetRamen** [saloni-15/Heel2Toe#80]
The elements in the footer are not aligned with each other. This *could* be aesthetically displeasing. ![image](https://user-images.githubusercontent.com/66806100/135756193-abbab678-6e6f-43f9-b3c7-0ad5b880e089.png)

Also, there isn't really a differentiator between the actual links and "quick links", so one may click on "quick links" because they think it is a link. ![image](https://user-images.githubusercontent.com/66806100/135756287-58a49d10-964e-4dbc-a58d-09926a710675.png)

**Comment by InternetRamen** [comment]
I'd like to be assigned this for hacktoberfest if this is a valid issue

**Comment by saloni-15** [comment]
sure @InternetRamen

**Comment by roy-rajarshi** [comment]
@InternetRamen Hey, I would like to work on this. I am new to open source and would like to contribute!

**Comment by InternetRamen** [comment]
> @InternetRamen Hey, I would like to work on this. I am new to open source and would like to contribute!

I'm sorry but I wanted to contribute
