### ISSUE TITLE
Add navbar on New Arrivals' page

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#84]
### Issue Description

- Include the same navbar as on the women's page and men's page on the New Arrivals' page i.e `arrivals.html`
  - Add links to `HOME    MEN    WOMEN    TRENDING    BEST SELLERS    CONTACT`
- Use `arrivals.css` for styling the page.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by ankitbajpai65** [comment]
Please assign me this issue.

**Comment by saloni-15** [comment]
sure @ankitbajpai65
