### ISSUE TITLE
Add navbar on Contact page.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#85]
### Issue Description

- Include the same navbar as on the women's page and men's page on the CONTACT page i.e `contact.html`
  - Add links to `HOME    MEN    WOMEN   NEW ARRIVALS   TRENDING    BEST SELLERS`
- Use `contact.css` for styling the page.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by kunal-umap** [comment]
I want to work on this , would you please assign me this ?

**Comment by saloni-15** [comment]
sure @kunal-umap

**Comment by kunal-umap** [comment]
I created a pull request Was it okay ?
