### ISSUE TITLE
Adding a carousel in New Arrival's Page

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#93]
## In `arrivals.html`
- Include a full width, self-moving Carousel/Image-slider having footwear-related images making it like a kind of commercials something like this 
![carousel](https://user-images.githubusercontent.com/75828760/135798700-4f6542a5-72d4-4f33-89e9-3550445ed896.gif)

- You can use a single text, but different background images as in [Best Seller's Page](https://saloni-15.github.io/Heel2Toe/best.html)
- Use some new images from the net and avoid using already existing images in assets.
- Include both men's and women's footwear.
- Use the same theme as the homepage.
- Provide screenshot/gif while creating PR.
- Add styling code in `arrivals.css`

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by ankitbajpai65** [comment]
@saloni-15 ,please assign me this issue.

**Comment by saloni-15** [comment]
sure @ankitbajpai65
