### ISSUE TITLE
Add product cards in Women's section.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#96]
### Issue Description

- Include the product images cards on the Women's page i.e `women.html` similarly as on the homepage

![image](https://user-images.githubusercontent.com/75828760/135850919-5f2a3ca7-dcb7-4dc4-842b-90377a0b24a9.png)

- Please keep the styling and spacing for the cards same as on the homepage.
- Add the images below this banner

![image](https://user-images.githubusercontent.com/75828760/135851138-3ddf84a2-3c41-4650-9b67-492be2e367bc.png)

- There are already 6 images in the images folder for women's footwear, add 3 or 6 more images and name the images accordingly.
- There should be 9 or 12 product cards on the Women's Page.
- Use `women.css` to style `women.html`
- Provide the screenshot/gif for the same while creating PR.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by thanh-cao** [comment]
@saloni-15  I can take this too if possible. Will be my first PR :)

**Comment by saloni-15** [comment]
> @saloni-15, please assign me this.

you must first complete issue #93, and please let somebody else get a chance too :)

**Comment by saloni-15** [comment]
> @saloni-15 I can take this too if possible. Will be my first PR :)

sure @thanh-cao

**Comment by thanh-cao** [comment]
Awesome! Please assign it to me :)
