### ISSUE TITLE
Add product cards in Men's section.

### ISSUE THREAD

**Issue by saloni-15** [saloni-15/Heel2Toe#97]
### Issue Description

- Include the product images cards on the Men's page i.e `men.html` similarly as on the homepage

![image](https://user-images.githubusercontent.com/75828760/135850919-5f2a3ca7-dcb7-4dc4-842b-90377a0b24a9.png)

- Please keep the styling and spacing for the cards same as on the homepage.
- Add the images below this banner

![image](https://user-images.githubusercontent.com/75828760/135852498-adbef6f9-3067-4609-b7a4-dfd18e91dec1.png)

- There are already 6 images in the images folder for men's footwear, add 3 or 6 more images and name the images accordingly.
- There should be 9 or 12 product cards on the Men's Page.
- Use `men.css` to style `men.html`
- Provide the screenshot/gif for the same while creating PR.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

**Comment by nafladiva** [comment]
Hey, I could work on this! Can you assign me?

**Comment by saloni-15** [comment]
Sure @nafladiva
